BEGIN;
DELETE FROM USERS;
INSERT INTO USERS(USER_ID, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY,
                  LAST_MODIFIED_DATE, USERNAME)
VALUES(1, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP,
       'JaneDNomad'),
      (2, CURRENT_USER, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_TIMESTAMP,
       'JohnDNomad');
COMMIT;
